version: '3'

services:

  app:
    hostname: app
    build: './src/app'
    ports:
      - '8080:80'

  docker-push:
    image: 'tmvdl/projects:enqueteiro'
    build: './src/app'

  github-release:
    image: 'github-release'
    build: './src'
